name: Test
on:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
      - run: make drafter
      - run: echo "${PWD}/bin" >> $GITHUB_PATH
      - run: go mod download
      - run: go test -v -race -cover ./...
  test-musl:
    name: test (alpine)
    runs-on: ubuntu-latest
    container:
      image: golang:1.15.2-alpine
    steps:
      - run: apk add --update build-base git wget
      - uses: actions/checkout@v2
      - run: DRAFTER_PLATFORM=linux-musl make drafter
      - run: echo "${PWD}/bin" >> $GITHUB_PATH
      - run: go mod download
      - run: go test -v -race -cover ./...
